
CREATE TABLE TB_MEMBER (
    member_seq INT NOT NULL AUTO_INCREMENT,
    user_id VARCHAR(10) NOT NULL,
    user_psw VARCHAR(20) NOT NULL,
    user_name VARCHAR(10) NOT NULL,
    is_del TINYINT NOT NULL DEFAULT 0,
    create_time DATETIME NOT NULL DEFAULT NOW(),
    update_time DATETIME NOT NULL DEFAULT NOW(),
    CONSTRAINT PRIMARY_SEQ_TB_MEMBER PRIMARY KEY (member_seq),
    CONSTRAINT UNIQUE_USERID_TB_MEMBER UNIQUE KEY (user_id)
);

CREATE TABLE TB_ARTICLE (
    article_seq INT NOT NULL AUTO_INCREMENT,
    member_seq INT NOT NULL,
    title VARCHAR(30) NOT NULL,
    contents VARCHAR(100) NOT NULL,
    is_del TINYINT NOT NULL DEFAULT 0,
    create_time DATETIME NOT NULL DEFAULT NOW(),
    update_time DATETIME NOT NULL DEFAULT NOW(),
    CONSTRAINT PRIMARY_SEQ_TB_ARTICLE PRIMARY KEY (article_seq),
    CONSTRAINT FK_MEMBER_SEQ_TB_ARTICLE FOREIGN KEY (member_seq) REFERENCES TB_MEMBER (member_seq)
);

